# Generated by Django 4.1.7 on 2023-04-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="panel.room",
                verbose_name="room",
            ),
        ),
    ]
